### PR TITLE
Fix worker vmo deletion if resource group is gone

### LINKED ISSUE #360: Shoot with VMO (VMSS Flex) cannot be deleted when the underlying resource group is deleted
/area quality
/kind bug
/priority 3
/platform azure

**What happened**:
Shoot with VMO (VMSS Flex) cannot be deleted when the underlying resource group is deleted

**What you expected to happen**:
Shoot with VMO (VMSS Flex) to be deleted when the underlying resource group is deleted

**How to reproduce it (as minimally and precisely as possible)**:

1. Create Shoot with VMO (VMSS Flex)

2. Delete manually the underlying resource group

3. Make sure that the Worker deletion fails with:

```yaml
status:
    lastError:
      codes:
      - ERR_CONFIGURATION_PROBLEM
      description: 'Error deleting worker: failed to cleanup machine dependencies:
        compute.VirtualMachineScaleSetsClient#List: Failure responding to request:
        StatusCode=404 -- Original Error: autorest/azure: Service returned an error.
        Status=404 Code="ResourceGroupNotFound" Message="Resource group ''shoot--foo--bar'
        could not be found."'
```

**Anything else we need to know?**:
See also https://github.com/gardener/machine-controller-manager-provider-azure/issues/19

**Environment**:

- Gardener version (if relevant):
- Extension version: v1.21.2
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by dkistner**
**How to categorize this PR?**
/kind bug
/platform azure

**What this PR does / why we need it**:
Fix deletion of vmss flex/vmo dependencies managed by the worker controller in case the underlying resource group is gone.
This unblocks the deletion flow for these cases.

**Which issue(s) this PR fixes**:
Fixes #360 

**Release note**:

```NONE

```

/invite @ialidzhikov @kon-angelo 
cc @stoyanr

### CODE REVIEW

File: pkg/azure/client/vmss.go [hunk 1]
```diff
@@ -72,6 +72,9 @@ func (c VmssClient) Create(ctx context.Context, resourceGroupName, name string,
 func (c VmssClient) Delete(ctx context.Context, resourceGroupName, name string) error {
 	future, err := c.client.Delete(ctx, resourceGroupName, name)
 	if err != nil {
+		if IsAzureAPINotFoundError(err) {
+			return nil
+		}
```
Comment (ialidzhikov) [inline pkg/azure/client/vmss.go:77]: Is it possible to add a unit test to make sure that we won't regress this in the future?

File: pkg/controller/worker/machineset_vmo.go [hunk 2]
```diff
@@ -147,7 +147,7 @@ func (w *workerDelegate) cleanupVmoDependencies(ctx context.Context, infrastruct
 
 func cleanupOrphanVMODependencies(ctx context.Context, client azureclient.Vmss, dependencies []azureapi.VmoDependency, resourceGroupName string) error {
 	vmoListAll, err := client.List(ctx, resourceGroupName)
-	if err != nil {
+	if err != nil && !azureclient.IsAzureAPINotFoundError(err) {
```
Comment (ialidzhikov) [inline pkg/controller/worker/machineset_vmo.go:150]: Is it possible to add a unit test to make sure that we won't regress this in the future?

File: pkg/azure/client/vmss.go (hunk 1 above)
Comment (dkistner) [reply pkg/azure/client/vmss.go:77]: For the `IsAzureAPINotFoundError` function exists unit tests. 
The Azure api return a 404 in case the resource group is gone.

Comment (dkistner) [reply pkg/azure/client/vmss.go:77]: Added a test for the case that the resource group gone. Sorry for the delay.

**Review by ialidzhikov — APPROVED** [review]
/lgtm

**Review by kon-angelo — APPROVED** [review]
/lgtm
