### PR TITLE
Fix restoration of infra with migrated network layout

### LINKED ISSUE #827: [CPM] Restoration of cluster fails if it's `Infrastructure` resource on the source `Seed` was annotated with `migration.azure.provider.extensions.gardener.cloud/zone`
**How to categorize this issue?**

/area control-plane-migration
/kind bug
/platform azure

**What happened**:
During control plane migration of an HA shoot cluster (using zones `z1`, `z2`, and `z3`), for which the infrastructure resource is annotated with `migration.azure.provider.extensions.gardener.cloud/zone`, the infrastructure resource is not successfully restored with the following error:
```
* creating Subnet: (Name "<vnet-name>-nodes-z3" / Virtual Network Name "<vnet-name>" / Resource Group "<resource-group-name>"): network.SubnetsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="NetcfgSubnetRangesOverlap" Message="Subnet '<vnet-name>-nodes-z3' is not valid because its IP address range overlaps with that of an existing subnet in virtual network '<vnet-name>'." Details=[]
  with azurerm_subnet.workers-z3,
  on main.tf line 167, in resource "azurerm_subnet" "workers-z3":
 167: resource "azurerm_subnet" "workers-z3" {
* deleting Subnet: (Name "<vnet-name>-nodes" / Virtual Network Name "<vnet-name>" / Resource Group "<resource-group-name>"): network.SubnetsClient#Delete: Failure sending request: StatusCode=400 -- Original Error: Code="InUseSubnetCannotBeDeleted" Message="Subnet<vnet-name>-nodes is in use by /subscriptions/<omitted>/resourceGroups/<resource-group-name>/providers/Microsoft.Network/networkInterfaces/<nic-id>-NIC/ipConfigurations/<nic-id>-NIC and cannot be deleted. In order to delete the subnet, delete all the resources within the subnet. See aka.ms/deletesubnet." Details=[]]
```

Basically, during the `restore` phase of control plane migration for the inrastructure resource the `provider-azure` extension tried to delete the `<vnet-name>-nodes` subnet and create `<vnet-name>-nodes-z3`. This seems to have happened because the infrastructure resource in the destination seed did not have an `migration.azure.provider.extensions.gardener.cloud/zone: "3"` annotation. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

The `migration.azure.provider.extensions.gardener.cloud/zone` annotation is put on the infrastructure resource via a mutating webhook here: https://github.com/gardener/gardener-extension-provider-azure/blob/b859d7beb856dcc3e461e36da8f6309ccd6115f5/pkg/webhook/infrastructure/layout.go#L132-L141

In this case, this mutating code did not get executed because of the following:
1. As part of normal reconciliation of the infrastructure resource its `.status.providerStatus` field is saved in the `.status.state.providerStatus`.
2. During the `migrate` phase of CPM `gardenlet` takes this `.status.state.savedProviderStatus` and saves it in the `ShootState`
3. During the `restore` phase of CPM `gardenlet` creates an infrastructure resource in the destination seed, then it copies the `.status.state.savedProviderStatus` from the `ShootState` and adds it to the infrastructure's `.status.state.savedProviderStatuss` field.
4. Afterwards, `gardenlet` annotates the the infrastructure resource with `gardener.cloud/operation: restore` to trigger restoration.

During the updates to the infrastructure resource in 3 and 4 the mutating webhook does not make any changes as it exits early due to these checks: https://github.com/gardener/gardener-extension-provider-azure/blob/b859d7beb856dcc3e461e36da8f6309ccd6115f5/pkg/webhook/infrastructure/layout.go#L117-L130

Even if the `status.providerState` is patched with the one from the `status.state.providerState`, the mutating webhook would still not perform any changes because the `status.providerState` would contain the following:
```
  "providerStatus": {
    "apiVersion": "azure.provider.extensions.gardener.cloud/v1alpha1",
    "availabilitySets": [],
    "kind": "InfrastructureStatus",
    "networks": {
      "layout": "MultipleSubnet",
```
Hence nil is returned here: https://github.com/gardener/gardener-extension-provider-azure/blob/b859d7beb856dcc3e461e36da8f6309ccd6115f5/pkg/webhook/infrastructure/layout.go#L128-L130

**What you expected to happen**:
Cluster to be restored successfully.

**Environment**:

- Gardener version (if relevant):
- Extension version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by plkokanov**
**How to categorize this PR?**

/area control-plane-migration
/kind bug
/platform azure

**What this PR does / why we need it**:
This PR modifies the layout mutator which adds the `migration.azure.provider.extensions.gardener.cloud/zone` annotation on the `Infrastructure` resource so that the annotation is also added during the `restore` phase of control plane migration in the following cases:
1. If the `.status.state` field is defined and is in the `azure.provider.extensions.gardener.cloud/v1alpha1` group version, then
    - If its `.data` field contains an entry for  `migration.azure.provider.extensions.gardener.cloud/zone`, then this entry is added as an annotation to the `Infrastructure` resource
2. If the `.status.state` field is defined and its type is [`InfrastructureState`](https://github.com/gardener/gardener-extension-provider-azure/blob/3b5becbae7761889d7bf7f476ede0eb6d5e4fd98/pkg/internal/infrastructure/state.go#L15-L22), then
    - If this `.state` field contains a `.savedProviderStatus` field and its `.networks.subnets` array contains a subnet for which the  `.migrated` field is true and the `.zone` field is not nil

Additionally, during reconciliation, if the new flow reconciler is used and the `migration.azure.provider.extensions.gardener.cloud/zone` annotation is present on the `Infrastructure` resource, then it is persisted in the `.status.state.data` map.

**Which issue(s) this PR fixes**:
Fixes #827

**Special notes for your reviewer**:

**Release note**:

```other operator
Fixed an issue that prevented the `Infrastructure` resource to be correctly restored during control plane migration, if the `Infrastructure` was previously migrated from a single subnet network layout to a multiple subnet network layout.
```

### CODE REVIEW

**Comment by plkokanov** [comment]
/hold 
I want to do a few more tests of the changes.

**Comment by plkokanov** [comment]
I finally have time to come back to this and I have done the following tests all of which passed without issues:
---
1. Create a cluster with 1 zone and 1 subnet layout using the **`terraform`** reconciler.
2. Migrate the cluster from single zone layout to multiple zone layout, which adds the `migration.azure.provider.extensions.gardener.cloud/zone` annotation.
3. Perform control plane migration to a destination seed which also uses the **`terraform`** reconciler.
4. Check that the `infrastructure` resource is created on the destination seed with the correct (preserved) `migration.azure.provider.extensions.gardener.cloud/zone` annotation.

---

1. Create a cluster with 1 zone and 1 subnet layout using the **`flow`** reconciler (seed has azure.provider.extensions.gardener.cloud/use-flow: "new")
2. Migrate the cluster from single zone layout to multiple zone layout.
3. Perform control plane migration to a destination seed which also uses the **`flow`** reconciler (seed has azure.provider.extensions.gardener.cloud/use-flow: "new")
4. Check that the `infrastructure` resource is created on the destination seed with the correct (preserved) `migration.azure.provider.extensions.gardener.cloud/zone` annotation.

---

1. Create a cluster with 1 zone and 1 subnet layout using the **`terraform`** reconciler.
2. Migrate the cluster from single zone layout to multiple zone layout.
3. Perform control plane migration to a destination seed which uses the **`flow`** reconciler for new shoots (azure.provider.extensions.gardener.cloud/use-flow: "new" )
4. Check that the `infrastructure` resource is created on the destination seed with the correct (preserved) `migration.azure.provider.extensions.gardener.cloud/zone` annotation.

---

@kon-angelo, does it make sense to preform similar tests when migrating the control plane from a seed that uses the `flow` reconciler to a seed that uses the `terraform` reconciler (if that is even supported)?

In the tests above, would it make a difference if the annotation used to enable the `flow` reconciler is `azure.provider.extensions.gardener.cloud/use-flow: "true"` vs `azure.provider.extensions.gardener.cloud/use-flow: "new"`

File: pkg/webhook/infrastructure/layout.go [hunk 1]
```diff
@@ -137,3 +145,45 @@ func mutate(_ context.Context, logger logr.Logger, newInfra, oldInfra *extension
...
+	}
+
+	if fsOk {
+		infraState, err := helper.InfrastructureStateFromRaw(infra.Status.State)
+		if err != nil {
+			return err
+		}
+
+		if migratedZone, ok := infraState.Data[azuretypes.NetworkLayoutZoneMigrationAnnotation]; ok {
+			infra.Annotations[azuretypes.NetworkLayoutZoneMigrationAnnotation] = migratedZone
```
Comment (ialidzhikov) [inline pkg/webhook/infrastructure/layout.go:166]:
```suggestion
			metav1.SetMetaDataAnnotation(&infra.ObjectMeta, azuretypes.NetworkLayoutZoneMigrationAnnotation, migratedZone)
```

File: pkg/webhook/infrastructure/layout.go [hunk 2]
```diff
@@ -104,6 +107,11 @@ func mutate(_ context.Context, logger logr.Logger, newInfra, oldInfra *extension
 		return nil
 	}
 
+	// If the current operation is restore, then mutation might be necessary as the zone migration annotation is not preserved during control plane migration.
+	if operation, ok := newInfra.Annotations[v1beta1constants.GardenerOperation]; ok && operation == v1beta1constants.GardenerOperationRestore {
+		return addMigratedZoneAnnotationDuringRestore(newInfra)
```
Comment (ialidzhikov) [inline pkg/webhook/infrastructure/layout.go:112]: Maybe

```suggestion
		extensionswebhook.LogMutation(logger, newInfra.Kind, newInfra.Namespace, newInfra.Name)
		return addMigratedZoneAnnotationDuringRestore(newInfra)
```

File: pkg/webhook/infrastructure/layout_test.go [hunk 3]
```diff
@@ -117,6 +119,72 @@ var _ = Describe("Mutate", func() {
...
+				Expect(err).To(BeNil())
+				newInfra.Status.State = &runtime.RawExtension{Raw: marshalled}
+
+				err = mutator.Mutate(context.TODO(), newInfra, newInfra)
+				Expect(err).To(BeNil())
+				v, ok := getLayoutMigrationAnnotation(newInfra)
+				Expect(ok).To(BeTrue())
+				Expect(v).To(Equal("2"))
+			})
+			It("should mutate the resource if the current 'gardener.cloud/operation' annotation is restore and has terraform state", func() {
```
Comment (ialidzhikov) [inline pkg/webhook/infrastructure/layout_test.go:144]:
```suggestion
			It("should mutate the resource if the current 'gardener.cloud/operation' annotation is 'restore' and has terraform state", func() {
```

**Review by kon-angelo — COMMENTED** [review]
@plkokanov excellent work. I will agree with the proposals from @ialidzhikov but otherwise,

/lgtm

**Review by ialidzhikov — APPROVED** [review]
/lgtm
